### ISSUE TITLE
Run script once without monitoring

### ISSUE THREAD

**Issue by kicumkicum** [sinclairzx81/hammer#8]
You hummer is cool! I can run node script with any module types without configure. I'm happy with it.

But I can not just run script. I use command `hammer run my-script.js` and hammer activate watch directory. I'm not want watch. I just run once. I use ctrl-c for any running my scripts.

How can I run script once? May be hammer has option for it?

**Comment by sinclairzx81** [comment]
@kicumkicum Hi! Glad you like working with Hammer :)

Hammer is mostly built as a development tool geared towards watch/reload workflows as the default. For running once, it's actually possible to build the application first and just run with node. So, consider the following run at the command line.

### Command Line

Builds `index.ts` into `target/app` and then runs with Node.

```bash
$ hammer build index.ts --dist target/app --platform node

$ cd target/app && node index.js
```

### Automate Command Line With Hammer Task

Use `hammer.mjs` to automate the above commands.

```typescript
// inside: hammer.mjs

export async function once() {

   await shell(`hammer build index.ts --dist target/app --platform node`)
   
   await shell(`cd target/app && node index.js`)
}
```
Which can be run with
```bash
$ hammer task once
```
Unfortunately, there's not too much documentation around hammer tasks, but they can offer a lot of flexibility to orchestrate custom workflows. Here's a few reference examples of using `hammer.mjs` to carry out a number of automation tasks for some of the projects I manage (also check each projects `package.json` for how these are tasks are setup as NPM `script` tasks)

https://github.com/sinclairzx81/typebox/blob/master/hammer.mjs
https://github.com/sinclairzx81/drift/blob/main/hammer.mjs
https://github.com/sinclairzx81/sidewinder/blob/master/hammer.mjs

Hope this helps!
S

**Comment by kicumkicum** [comment]
Thanky for you answer, @sinclairzx81 

I have next case. Application on Next.js with native import and zero configuration build. I want write some scripts - utils, tools - for different tasks. It not part of application, but it use some code from application.

I can't run my tools with node, because differnt module system (commonJs, native) is problem. I must use build tool - webpack, etc - for fix it problem, but I not want more difficult for my project. I want keep zero build configuration.

Hammer is great tools for it. It just run my scripts. But I want just run, once, with out watching changes.

May be you can add this functionality in hameer?☺️

**Comment by sinclairzx81** [comment]
@kicumkicum Hiya,

> I have next case. Application on Next.js with native import and zero configuration build. I want write some scripts - utils, tools - for different tasks. It not part of application, but it use some code from application.

I think in this case, the best option may be to implement this functionality with `esbuild` https://esbuild.github.io/ rather than using Hammer. Hammer is written mostly as a build time development system, so isn't really something you would use for production. It is possible to use `hammer task taskname` (as in the example above) to build and run code once, however the cleanest option may be to use the `esbuild` bundler directly to compile your ESM modules (it requires little configuration to use, and is what Hammer uses internally...it's very easy to use)

Also, there are actually dedicated tools like `ts-node` https://www.npmjs.com/package/ts-node which will allow you to run Node with minimal configuration required (I think tsconfig.json is optional), so this would let you run script from the command line if this is what you need.

As for adding this functionality to Hammer, I won't be able to implement for this version of the tool, but may consider on the next version when I get around to integrating https://github.com/sinclairzx81/drift into Hammer (which would require a re-design of the CLI).

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@kicumkicum Might close of this issue for now. I think the functionality you need could either be implemented through hammer tasks, or by taking a dependency on `esbuild` and implementing directly. Running once is a bit outside the scope (or intent) of this tool, but may review things again in the next major revision.

All the best!
S

**Comment by kicumkicum** [comment]
> but may review things again in the next major revision

I will wait for it 😸
